# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_time": "01_converters.ipynb",
         "get_date": "01_converters.ipynb",
         "add_datetime_column": "01_converters.ipynb",
         "get_list_of_hourfolders": "01_converters.ipynb",
         "get_hour_subfiles": "01_converters.ipynb",
         "convert_4hfiles_to_df": "01_converters.ipynb",
         "cols_to_numeric": "03_io.ipynb",
         "convert_dayfiles_to_df": "01_converters.ipynb",
         "convert_month_to_df": "01_converters.ipynb",
         "run_month_conversion_parallel": "01_converters.ipynb",
         "d": "02_db_tools.ipynb",
         "mars_years": "02_db_tools.ipynb",
         "tables": "02_db_tools.ipynb",
         "views": "02_db_tools.ipynb",
         "view_dic": "02_db_tools.ipynb",
         "get_MY_bracket": "02_db_tools.ipynb",
         "get_MY_for_date": "02_db_tools.ipynb",
         "mcsdate2datetime": "02_db_tools.ipynb",
         "MarsTimer": "02_db_tools.ipynb",
         "DateConverter": "02_db_tools.ipynb",
         "sqlize": "02_db_tools.ipynb",
         "SQLizer": "02_db_tools.ipynb",
         "add_utc_col": "02_db_tools.ipynb",
         "MCSDB": "02_db_tools.ipynb",
         "read_list_to_df": "03_io.ipynb",
         "L2Reader": "03_io.ipynb",
         "DBManager": "03_io.ipynb",
         "get_header_data": "03_io.ipynb"}

modules = ["converters.py",
           "db_tools.py",
           "io.py"]

doc_url = "https://michaelaye.github.io/pymcs/"

git_url = "https://github.com/michaelaye/pymcs/tree/master/"

def custom_doc_links(name): return None
